"use client";

import {
  Monitor,
  Cpu,
  Laptop,
  Tv,
  Server,
  HardDrive,
  Printer,
  Smartphone,
  Phone,
  Package,
  Tablet,
  Wifi,
  Router,
  Network,
  Cable,
  Battery,
  Camera,
  Keyboard,
  Mouse,
  Headphones,
  Speaker,
  MemoryStick,
  CircuitBoard,
  Zap,
  Radio,
  Bluetooth,
  Usb,
  Disc,
  Save,
  FileText,
  Folder,
  FolderOpen,
  Layers,
  Box,
  Boxes,
  Truck,
  ShoppingCart,
  CreditCard,
  Lock,
  Unlock,
  Key,
  Settings,
  Cog,
  Wrench,
  QrCode,
  Barcode,
  Fingerprint,
  Video,
  Gamepad2,
  Watch,
  Gauge,
  Thermometer,
  Fan,
  Plug,
  PlugZap,
  BatteryCharging,
  Lightbulb,
  Power,
  Database,
  Cloud,
  CloudUpload,
  Share2,
  Link,
  Link2,
  Globe,
  ScanLine,
  type LucideIcon,
} from "lucide-react";

// Mapa completo de ícones suportados (built-in + customizados).
// Se o admin digitar um nome de ícone que NÃO está nesta lista, o sistema
// cai no ícone padrão (Package) — veja a lista completa em lucide.dev/icons
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  MONITOR: Monitor,
  CPU: Cpu,
  NOTEBOOK: Laptop,
  TV: Tv,
  RACK: Server,
  SERVIDOR: HardDrive,
  IMPRESSORA: Printer,
  IMPRESSORA_ZEBRA: Printer,
  SMARTPHONE: Smartphone,
  TELEFONE_FIXO: Phone,
  // Ícones extras para categorias customizadas
  Package,
  Tablet,
  Wifi,
  Router,
  Network,
  Cable,
  Battery,
  Camera,
  Keyboard,
  Mouse,
  Headphones,
  Speaker,
  HardDriveDownload: HardDrive,
  MemoryStick,
  CircuitBoard,
  Zap,
  Radio,
  Bluetooth,
  Usb,
  Disc,
  Save,
  FileText,
  Folder,
  FolderOpen,
  Layers,
  Box,
  Boxes,
  Truck,
  ShoppingCart,
  CreditCard,
  Lock,
  Unlock,
  Key,
  Settings,
  Cog,
  Wrench,
  QrCode,
  Barcode,
  Fingerprint,
  Video,
  Gamepad2,
  Watch,
  Gauge,
  Thermometer,
  Fan,
  Plug,
  PlugZap,
  BatteryCharging,
  Lightbulb,
  Power,
  Database,
  Cloud,
  CloudUpload,
  Share2,
  Link,
  Link2,
  Globe,
  ScanLine,
};

export function CategoryIcon({
  categoria,
  className,
  iconName,
}: {
  categoria: string;
  className?: string;
  iconName?: string; // override: usar ícone pelo nome
}) {
  // Prioridade: iconName > categoria > Package
  const Icon =
    (iconName && CATEGORY_ICONS[iconName]) ||
    CATEGORY_ICONS[categoria] ||
    Package;
  return <Icon className={className} />;
}

// Verifica se um nome de ícone é reconhecido (usado para dar feedback visual
// no formulário de categoria quando o admin digita um nome customizado)
export function isIconeConhecido(nome: string): boolean {
  return nome in CATEGORY_ICONS;
}
